"""empty message

Revision ID: 7214fe9bac01
Revises: 5566e07e81a5
Create Date: 2022-09-28 21:32:03.013043

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7214fe9bac01'
down_revision = '5566e07e81a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('favorites', 'planet_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('favorites', 'people_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('favorites', 'people_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('favorites', 'planet_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
